### PR TITLE
Bump kubernetes version to 1.7.6 and step version to 3.5.0

### PR DESCRIPTION
**Pull request by alexkappa**

### CODE REVIEW

**Comment by jwolski2** [comment]
@alexkappa Thanks for the contrib. The latest release looks to be 1.7.6. Can you modify the version number and update the Changelog section in the README file to reflect your update. When done, I'll merge. <3

**Comment by alexkappa** [comment]
Hi @jwolski2 of course!

**Comment by alexkappa** [comment]
@jwolski2 updated. Thanks for the quick check 👍

**Comment by jwolski2** [comment]
lgtm

**Pull request merged**
