### PR TITLE
Update `kubectl` to version `1.3.4`.

### PR DESCRIPTION
**Pull request by MaikuMori**
Note: I didn't add all the new options and commands. My guess is that most people only use the `command` parameter anyway.

### CODE REVIEW

**Comment by MaikuMori** [comment]
I managed to bring the filesize down, but maybe it's time to increase the limit on Wercker side? Having to compress the executable is somewhat silly.

**Comment by hatchan** [comment]
@MaikuMori Noticed the `kubectl` is just getting bigger as well, so changing the max size probably a good idea. Unfortunately I can only check tomorrow for those changes. So waiting with this PR til tomorrow, so we can get rid of that last commit.

Also, it might be a good idea to directly fetch the kubectl binary from: ```https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl```

**Comment by MaikuMori** [comment]
I rewrote the history still leaving 2 commits. It's now using version `1.3.4` and your suggested download path.

**Comment by termie** [comment]
works for me, will merge

**Comment by MaikuMori** [comment]
There is still the issue of filesize. The compression thing I did is kinda hacky way to get around the problem.

**Comment by hatchan** [comment]
@MaikuMori We upped the max limit. We're removing thecompression in a future PR. See: https://github.com/wercker/step-kubectl/pull/12

**Pull request merged**
